### ISSUE TITLE
Unable to export contracts from BQ to GCS

### ISSUE THREAD

**Issue by whydna** [blockchain-etl/ethereum-etl-postgres#12]
```Dataset 'crypto-developer:export_temp_dataset' successfully created.
 from `bigquery-public-data.crypto_ethereum.contracts`,'), '}') as function_sighashes,
'C:\Users\xxx\AppData\Local\Google\Cloud' is not recognized as an internal or external command,
operable program or batch file.
Exporting BigQuery table export_temp_dataset.flattened_contracts
Extracting export_temp_dataset.flattened_contracts to gs://ether-123/export_temp_dataset.flattened_contracts_raw/*.gz ...
BigQuery error in extract operation: Error processing job 'crypto-
developer:bqjob_r1030b112cfb90c68_0000018090afc78a_1': Not found: Table crypto-
developer:export_temp_dataset.flattened_contracts was not found in location US
Composing files in gs://ether-123export_temp_dataset.flattened_contracts_raw/ to gs://ether-123export_temp_dataset.flattened_contracts_composed/
Composing files in gs://ether-123export_temp_dataset.flattened_contracts_composed/ to gs://ether-123export_temp_dataset.flattened_contracts/
CommandException: 1 files/objects could not be removed.
CommandException: 1 files/objects could not be removed.
CommandException: No URLs matched: gs://ether-123/export_temp_dataset.flattened_contracts/*
CommandException: 1 file/object could not be transferred.
```

**Comment by medvedev1088** [comment]
@bsh98, would appreciate if you could take a look

**Comment by bsh98** [comment]
> ```
>  from `bigquery-public-data.crypto_ethereum.contracts`,'), '}') as function_sighashes,
> 'C:\Users\xxx\AppData\Local\Google\Cloud' is not recognized as an internal or external command,
> operable program or batch file.
> Exporting BigQuery table export_temp_dataset.flattened_contracts
> Extracting export_temp_dataset.flattened_contracts to gs://ether-123/export_temp_dataset.flattened_contracts_raw/*.gz ...
> BigQuery error in extract operation: Error processing job 'crypto-
> developer:bqjob_r1030b112cfb90c68_0000018090afc78a_1': Not found: Table crypto-
> developer:export_temp_dataset.flattened_contracts was not found in location US
> Composing files in gs://ether-123export_temp_dataset.flattened_contracts_raw/ to gs://ether-123export_temp_dataset.flattened_contracts_composed/
> Composing files in gs://ether-123export_temp_dataset.flattened_contracts_composed/ to gs://ether-123export_temp_dataset.flattened_contracts/
> CommandException: 1 files/objects could not be removed.
> CommandException: 1 files/objects could not be removed.
> CommandException: No URLs matched: gs://ether-123/export_temp_dataset.flattened_contracts/*
> CommandException: 1 file/object could not be transferred.
> ```

Thank you for pointing this out!  It looks like the temp table for contracts isn't being created since the query is being truncated by a comment.  The issue should be resolved in https://github.com/blockchain-etl/ethereum-etl-postgres/pull/13.  Hope this helps.
